services:
  - type: web
    name: vitibrasil-tech-challenge
    env: python
    # buildCommand: "" # Render geralmente detecta requirements.txt para Python, mas é mais explícito adicionar:
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn src.app.web.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION # Opcional: Especifique a versão do Python se necessário
        value: "3.10" # Exemplo, ajuste para a versão que você usa (ex: 3.8, 3.9, 3.10, 3.11, 3.12)
      - key: JWT_SECRET
        # IMPORTANTE: Altere este valor para um segredo forte e único
        # diretamente no dashboard de configuração de ambiente do Render,
        # não o comite no seu repositório se for um segredo real.
        # O valor aqui pode ser um placeholder ou um valor padrão para builds.
        value: "SEU_SEGREDO_FORTE_CONFIGURADO_NO_RENDER"
      # Se você decidir usar um banco de dados persistente como o PostgreSQL do Render:
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: nomeDoSeuBancoDeDadosNoRender # Substitua pelo nome do seu serviço de BD no Render
      #     property: connectionString