services:
  - type: web
    name: vitibrasil-tech-challenge
    env: python
    buildCommand: ""
    startCommand: "gunicorn src.app.web.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
    envVars:
      - key: JWT_SECRET
        value: MEUSEGREDOAQUI